; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "TapMap"
#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-dev"
#endif
#ifndef MyAppExePath
  #define MyAppExePath "tapmap.exe"
#endif
#define MyAppDir ExtractFileDir(MyAppExePath)
#ifndef MySetupIcon
  #define MySetupIcon "tapmap.ico"
#endif
#ifndef MyOutputDir
  #define MyOutputDir "..\..\dist"
#endif
#ifndef MyOutputBaseFilename
  #define MyOutputBaseFilename "TapMap-0.0.0-dev-Setup"
#endif
#define MyAppPublisher "Tip Teknologi i Praksis AS"
#define MyAppURL "https://tapmap.tip.no"
#define MyAppExeName "tapmap.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{42F6DEC4-B33B-4372-96EB-B54ADF823919}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir={#MyOutputDir}
OutputBaseFilename={#MyOutputBaseFilename}
SolidCompression=yes
WizardStyle=modern dynamic
SetupIconFile={#MySetupIcon}
SignTool=signtool
SignedUninstaller=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppExePath}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDir}\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; \
    Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; \
    Flags: nowait postinstall skipifsilent runasoriginaluser

[Code]

// TapMap manages autostart at runtime.
// The installer only removes recognized tasks during migration and uninstall.
//
// "Type" is a reserved word in Pascal Script and can't be read as a COM
// property name here. Trigger.UserId and Action.Path are checked instead.

function TapMapNormalizeUserId(const Raw: String): String;
var
  SepPos: Integer;
  Name: String;
begin
  Name := Raw;
  SepPos := Pos('\', Name);
  if SepPos > 0 then
    Name := Copy(Name, SepPos + 1, MaxInt);
  Result := Lowercase(Trim(Name));
end;

function TapMapNormalizePath(const Raw: String): String;
var
  Value: String;
begin
  Value := Trim(Raw);
  if (Length(Value) >= 2) and (Value[1] = '"') and (Value[Length(Value)] = '"') then
    Value := Copy(Value, 2, Length(Value) - 2);
  Result := Lowercase(Value);
end;

function TapMapDeleteTaskIfRecognized(): Boolean;
var
  Service, Folder, Task, Definition, Principal, Triggers, Trigger, Actions, Action: Variant;
  TriggerUserIdVar: Variant;
  CurrentUser, ExePath, TriggerUserId, PrincipalUserId, ActionPath: String;
  LogonType, RunLevel, TriggerCount, ActionCount: Integer;
  Recognized: Boolean;
begin
  Result := False;

  try
    Service := CreateOleObject('Schedule.Service');
    Service.Connect();
    Folder := Service.GetFolder('\');
  except
    Exit; // Can't reach Task Scheduler; do nothing.
  end;

  try
    Task := Folder.GetTask('TapMap');
  except
    Exit;
  end;

  CurrentUser := TapMapNormalizeUserId(GetUserNameString());
  ExePath := TapMapNormalizePath(ExpandConstant('{app}\{#MyAppExeName}'));
  Recognized := False;

  try
    Definition := Task.Definition;
    Principal := Definition.Principal;
    Triggers := Definition.Triggers;
    Actions := Definition.Actions;

    LogonType := Principal.LogonType;
    RunLevel := Principal.RunLevel;
    TriggerCount := Triggers.Count;
    ActionCount := Actions.Count;
    PrincipalUserId := Principal.UserId;

    if (LogonType = 3) and (RunLevel = 0) and (TriggerCount = 1) and (ActionCount = 1) then
    begin
      Trigger := Triggers.Item(1);
      Action := Actions.Item(1);
      TriggerUserIdVar := Trigger.UserId;
      if VarIsNull(TriggerUserIdVar) or VarIsEmpty(TriggerUserIdVar) then
        TriggerUserId := ''
      else
        TriggerUserId := TriggerUserIdVar;
      ActionPath := Action.Path;

      // The old installer's task has no Trigger.UserId. Treat that as
      // missing information, not a mismatch. A UserId that IS set must match.
      if ((TriggerUserId = '') or (TapMapNormalizeUserId(TriggerUserId) = CurrentUser)) and
         (TapMapNormalizeUserId(PrincipalUserId) = CurrentUser) and
         (TapMapNormalizePath(ActionPath) = ExePath) then
        Recognized := True;
    end;
  except
    Recognized := False; // Unreadable fields: assume not ours.
  end;

  if not Recognized then
    Exit;

  try
    Folder.DeleteTask('TapMap', 0);
    Result := True;
  except
    // Ignore delete failures; uninstall continues.
  end;
end;

function TapMapDeleteLegacyInstallerTaskIfRecognized(): Boolean;
var
  Service, Folder, Task, Definition, Principal, Triggers, Trigger, Actions, Action: Variant;
  TriggerUserIdVar, ActionArgumentsVar: Variant;
  CurrentUser, ExePath, TriggerUserId, PrincipalUserId, ActionPath, ActionArguments: String;
  LogonType, RunLevel, TriggerCount, ActionCount: Integer;
  Recognized: Boolean;
begin
  Result := False;

  try
    Service := CreateOleObject('Schedule.Service');
    Service.Connect();
    Folder := Service.GetFolder('\');
  except
    Exit; // Can't reach Task Scheduler; do nothing.
  end;

  try
    Task := Folder.GetTask('TapMap');
  except
    Exit;
  end;

  CurrentUser := TapMapNormalizeUserId(GetUserNameString());
  ExePath := TapMapNormalizePath(ExpandConstant('{app}\{#MyAppExeName}'));
  Recognized := False;

  try
    Definition := Task.Definition;
    Principal := Definition.Principal;
    Triggers := Definition.Triggers;
    Actions := Definition.Actions;

    LogonType := Principal.LogonType;
    RunLevel := Principal.RunLevel;
    TriggerCount := Triggers.Count;
    ActionCount := Actions.Count;
    PrincipalUserId := Principal.UserId;

    if (LogonType = 3) and (RunLevel = 0) and (TriggerCount = 1) and (ActionCount = 1) then
    begin
      Trigger := Triggers.Item(1);
      Action := Actions.Item(1);

      TriggerUserIdVar := Trigger.UserId;
      if VarIsNull(TriggerUserIdVar) or VarIsEmpty(TriggerUserIdVar) then
        TriggerUserId := ''
      else
        TriggerUserId := TriggerUserIdVar;

      ActionArgumentsVar := Action.Arguments;
      if VarIsNull(ActionArgumentsVar) or VarIsEmpty(ActionArgumentsVar) then
        ActionArguments := ''
      else
        ActionArguments := ActionArgumentsVar;

      ActionPath := Action.Path;

      // The legacy installer task has no Trigger.UserId or arguments.
      if (TriggerUserId = '') and (ActionArguments = '') and
         (TapMapNormalizeUserId(PrincipalUserId) = CurrentUser) and
         (TapMapNormalizePath(ActionPath) = ExePath) then
        Recognized := True;
    end;
  except
    Recognized := False; // Unreadable fields: assume not ours.
  end;

  if not Recognized then
    Exit;

  try
    Folder.DeleteTask('TapMap', 0);
    Result := True;
  except
    // Ignore delete failures; installation continues.
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    TapMapDeleteLegacyInstallerTaskIfRecognized();
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  MarkerPath: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    TapMapDeleteTaskIfRecognized();

    // Remove the setup marker so a reinstall enables autostart by default.
    MarkerPath := ExpandConstant('{userappdata}\TapMap\autostart_setup_completed.marker');
    if FileExists(MarkerPath) then
      DeleteFile(MarkerPath);
  end;
end;
