blank_issues_enabled: false

contact_links:
  - name: Feature requests
    url: https://github.com/olalie/tapmap/discussions
    about: Use Discussions to suggest new features or improvements.

  - name: Questions
    url: https://github.com/olalie/tapmap/discussions
    about: Use Discussions to ask questions about TapMap.
