name: macOS Pipeline

on:
  workflow_dispatch:
    inputs:
      mode:
        description: Build or release
        type: choice
        options:
          - build
          - release
        default: build

  workflow_call:
    inputs:
      mode:
        description: Build or release
        required: false
        type: string
        default: build

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:
      - id: matrix
        shell: bash
        run: |
          echo "Mode is: ${{ inputs.mode }}"

          if [ "${{ inputs.mode }}" = "release" ]; then
            echo 'matrix={"include":[{"arch":"arm64"},{"arch":"x86_64"}]}' >> "$GITHUB_OUTPUT"
          else
            echo 'matrix={"include":[{"arch":"arm64"}]}' >> "$GITHUB_OUTPUT"
          fi

      - name: Show generated matrix
        run: |
          echo '${{ steps.matrix.outputs.matrix }}'

  build:
    needs: prepare

    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    runs-on: macos-latest

    steps:
      - name: Show matrix values
        shell: bash
        run: |
          echo "Mode : ${{ inputs.mode }}"
          echo "Arch : ${{ matrix.arch }}"
          echo "Runner architecture:"
          uname -m

      - name: Done
        run: echo "Dynamic matrix test completed."
