name: Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  # docker:
  #   name: Docker Tests
  #   uses: ./.github/workflows/pipeline-docker.yaml
  #   with:
  #     mode: release

  # linux:
  #   name: Linux Build
  #   uses: ./.github/workflows/pipeline-linux.yaml

  windows:
    name: Windows Build
    uses: ./.github/workflows/pipeline-windows.yaml

  # macos-arm64:
  #   name: macOS (Apple Silicon)
  #   uses: ./.github/workflows/pipeline-macos.yaml
  #   with:
  #     architecture: arm64
  #   secrets: inherit

  # macos-x86_64:
  #   name: macOS (Intel)
  #   uses: ./.github/workflows/pipeline-macos.yaml
  #   with:
  #     architecture: x86_64
  #   secrets: inherit

  publish-test:
    name: Test artifact download
    needs:
      - windows
      # - macos-arm64
      # - macos-x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Show downloaded artifacts
        run: |
          find artifacts -type f
