name: Release

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  docker:
    name: Docker Tests
    uses: ./.github/workflows/pipeline-docker.yaml
    with:
      mode: release

  linux:
    name: Linux Build
    uses: ./.github/workflows/pipeline-linux.yaml
    with:
      mode: release

  windows:
    name: Windows Build
    uses: ./.github/workflows/pipeline-windows.yaml
    with:
      mode: release

  macos:
    name: macOS Build
    uses: ./.github/workflows/pipeline-macos.yaml
    with:
      mode: release
    secrets: inherit
